
import type {Metadata} from "next";
import {ReactNode} from "react";
import {I18nProvider} from "@/provider/I18nProvider";
import {resources} from "@/i18n/resources";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                       children,
                                       params

                                   }: Readonly<{
    children: ReactNode;
    params: any
}>) {
    const {lng} =await params
    return (
        <html>
        <body>
        <I18nProvider lng={lng} >
            {children}
        </I18nProvider>

        </body>
        </html>
    );
}
